name: Deploy to VM
 
on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: self-hosted
 
    env:
      VM_HOST: 10.3.15.56
      VM_USER: azubi           
      DEST_DIR: ~/ci_cd_test    
      SSH_PORT: "22"
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Write SSH key (Windows)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "$HOME\.ssh" -Force | Out-Null
          $keyPath = "$HOME\.ssh\id_rsa"
          Set-Content -Path $keyPath -Value @"
          ${{ secrets.SSH_PRIVATE_KEY }}
          "@ -NoNewline
          icacls $keyPath /inheritance:r /grant:r "$($env:USERNAME):(R)" | Out-Null
          ssh-keyscan -p $env:SSH_PORT -H $env:VM_HOST | Out-File -FilePath "$HOME\.ssh\known_hosts" -Append
 
      - name: Ensure destination exists
        shell: pwsh
        run: |
          ssh -i "$HOME\.ssh\id_rsa" -p "$env:SSH_PORT" "$env:VM_USER@$env:VM_HOST" "mkdir -p '$env:DEST_DIR'"
 
      - name: Deploy via rsync
        shell: bash
        run: |
          rsync -az --delete \
            --exclude ".git" \
            --exclude ".github" \
            -e "ssh -i $HOME/.ssh/id_rsa -p $SSH_PORT" \
            ./ "$VM_USER@$VM_HOST:$DEST_DIR"
 
    