name: Deploy to VM
 
on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: self-hosted
 
    defaults:
      run:
        shell: powershell
 
    env:
      VM_HOST: 10.3.15.56
      VM_USER: azubi
      DEST_DIR: ~/ci_cd_test
      SSH_PORT: "22"
      KEX: curve25519-sha256,diffie-hellman-group14-sha256
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Write SSH key
        run: |
          New-Item -ItemType Directory -Path "$HOME\.ssh" -Force | Out-Null
          $keyPath = "$HOME\.ssh\id_rsa"
          @"
          ${{ secrets.SSH_PRIVATE_KEY }}
          "@ | Set-Content -Path $keyPath -NoNewline
          icacls $keyPath /inheritance:r /grant:r "$($env:USERNAME):(R)" | Out-Null
 
      - name: Add host key (compat KEX)
        run: |
          ssh-keyscan -p $env:SSH_PORT -o "KexAlgorithms=$env:KEX" -H $env:VM_HOST |
            Out-File -FilePath "$HOME\.ssh\known_hosts" -Append
 
      - name: Ensure destination exists (do not quote ~)
        run: |
          ssh -i "$HOME\.ssh\id_rsa" -p "$env:SSH_PORT" -o "KexAlgorithms=$env:KEX" `
            "$env:VM_USER@$env:VM_HOST" "mkdir -p $env:DEST_DIR"
 
      - name: Deploy via scp (do not quote ~)
        run: |
          scp -i "$HOME\.ssh\id_rsa" -P "$env:SSH_PORT" -o "KexAlgorithms=$env:KEX" `
            -r . "$env:VM_USER@$env:VM_HOST:$env:DEST_DIR"