name: Update Files with SCP

on:
  push: 
    branches: 
      - main
jobs:
  deploy: 
    runs-on: self-hosted

    steps: 
      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name: SSH Setup 
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 10.3.15.56 >> ~/.ssh/known_hosts 

      - name: Copy files via SCP
        run: |
          scp -r ./ azubi@10.3.15.56:/home/azubi/
