name: Deploy to VM
 
on:
  push:
    branches: [ main ]
 
jobs:
  deploy:
    runs-on: self-hosted
 
    env:
      VM_HOST: 10.3.15.56
      VM_USER: username
      DEST_DIR: /pfad/zum/ziel
      SSH_PORT: "22"
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
      - name: Trust host key
        run: ssh-keyscan -p "$SSH_PORT" -H "$VM_HOST" >> ~/.ssh/known_hosts
 
      - name: Ensure destination exists
        run: ssh -p "$SSH_PORT" "$VM_USER@$VM_HOST" "mkdir -p '$DEST_DIR'"
 
      - name: Deploy via rsync
        run: |
          rsync -az --delete \
            --exclude ".git" \
            --exclude ".github" \
            -e "ssh -p $SSH_PORT" \
            ./ "$VM_USER@$VM_HOST:$DEST_DIR"